name: '@wizbii/nest-bugsnag'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn
      - uses: actions/cache@v3
        id: cache-install
        with:
          path: ./*
          key: ${{ github.sha }}
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Lint lib
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Test lib
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: restore-install
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Build lib
        run: yarn clean:build
